# Generated by Django 3.2 on 2021-05-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20210504_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='death',
            field=models.DateField(blank=True, help_text='Leave empty if alive', null=True),
        ),
    ]
