# Generated by Django 3.2 on 2021-05-04 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20210504_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='movies',
        ),
        migrations.RemoveField(
            model_name='director',
            name='movies',
        ),
        migrations.RemoveField(
            model_name='writer',
            name='movies',
        ),
        migrations.AlterField(
            model_name='actor',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.person'),
        ),
        migrations.AlterField(
            model_name='director',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.person'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.person'),
        ),
    ]
