# Generated by Django 3.2 on 2021-05-04 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20210504_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.person', unique=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.person', unique=True),
        ),
        migrations.AlterField(
            model_name='writer',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.person', unique=True),
        ),
    ]
