# Generated by Django 3.2 on 2021-05-04 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_alter_actor_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.person', unique=True),
        ),
    ]
