# Generated by Django 3.2 on 2021-05-04 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_alter_actor_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='actor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.person'),
        ),
        migrations.AlterField(
            model_name='director',
            name='director',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.person'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='studio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='movies.studio'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='writer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.person'),
        ),
    ]
